- name: Crear nuevo grupo en Zabbix
  uri:
    url: "{{ zabbix_api_url }}"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "hostgroup.create"
      params:
        name: "{{ add_group_name }}"
        flags: "{{ add_group_enable }}"
        internal: "{{ add_group_internal }}"
        groupids: "{{ zabbix_group_frontend.json.result[0].groupid }}"
      auth: "{{ zabbix_auth.json.result }}"
      id: 3
    validate_certs: no
