---
- name: Obtener token de autenticacion en Zabbix
  gather_facts: false
  become: false
  delegate_to: localhost
  include_tasks: get_token_zabbix.yml

- name: Crear nuevo grupo en Zabbix
  gather_facts: false
  become: false
  delegate_to: localhost
  include_tasks: add_group_name.yml

