---
- name: Zabbix
  #hosts: '{{ worker }}'
  hosts: master
  become: yes
  vars:
    ansible_become_password: "{{ ansible_ssh_pass }}"

  tasks:

### ACTUALIZAR REPOLIST

    - name: Actualizar lista de paquetes
      yum:
        name: '*'
        state: latest
        update_cache: yes

### INSTALAR DEPENDENCIAS

    - name: Install Pre-Requisitos
      yum:
        name:
          - httpd
          - epel-release
          - java-11-openjdk-devel
          - python3-pip
          - nano
          - wget
          - curl
        state: present

    - name: pip Install
      pip:
        name:
          - pexpect
        state: present

### VERIFICAR SERVICIOS

    - name: Status Apache
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: Configurar Apache como proxy HTTP para Kibana
      template:
        src: templates/proxyhttpd.conf.j2
        dest: /etc/httpd/conf.d/kibana.conf
        mode: 0644

    - name: Habilitar tráfico HTTP en el firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Configurar permisos de SELinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: true

