---
- name: Crear nuevo grupo en Zabbix
  hosts: all
  become: true
  vars:
    zabbix_api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    zabbix_username: "Admin"
    zabbix_password: "zabbix"
    zabbix_group_name: "migrupo"
    zabbix_group_enable: 0  # 0 para deshabilitar, 1 para habilitar
    zabbix_group_internal: 1  # 1 para grupo interno, 0 para externo
    zabbix_group_front_end: 1  # "0" para "System default"

  tasks:
    - name: Obtener token de autenticación en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ zabbix_username }}"
            password: "{{ zabbix_password }}"
          id: 1
          auth: null
        validate_certs: no
      register: zabbix_auth

    - name: Obtener ID del grupo "Frontend access"
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostgroup.get"
          params:
            output: "extend"
            filter:
              name: "Frontend access"
          auth: "{{ zabbix_auth.json.result }}"
          id: 2
        validate_certs: no
      register: zabbix_group_frontend

    - name: Crear nuevo grupo en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostgroup.create"
          params:
            name: "{{ zabbix_group_name }}"
            flags: "{{ zabbix_group_enable }}"
            internal: "{{ zabbix_group_internal }}"
            groupids: "{{ zabbix_group_frontend.json.result[0].groupid }}"
          auth: "{{ zabbix_auth.json.result }}"
          id: 3
        validate_certs: no