---
- name: Crear grupo de usuarios en Zabbix
  hosts: localhost
  gather_facts: no

  vars:
    zabbix_api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    zabbix_api_user: "admin"
    zabbix_api_pass: "zabbix"
    add_group_name: "migrupo"

  tasks:
    - name: Obtener token de autenticación de Zabbix API
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: application/json-rpc
        body_format: json
        body:
          jsonrpc: "2.0"
          method: user.login
          params:
            user: "{{ zabbix_api_user }}"
            password: "{{ zabbix_api_pass }}"
          id: 1
      register: auth_result
      no_log: true

    - name: Crear grupo de usuarios en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: application/json-rpc
          Authorization: "Bearer {{ auth_result.json.result }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: usergroup.create
          params:
            name: "{{ add_group_name }}"
          id: 2
      register: create_group_result

    - name: Mostrar resultado de la creación del grupo
      debug:
        var: create_group_result.json
