---
- name: Crear grupo en Zabbix
  hosts: localhost
  gather_facts: false

  vars:
    api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    api_user: "Admin"
    api_pass: "zabbix"
    group_name: "demo1"

  tasks:
    - name: Obtener token de autenticación
      uri:
        url: "{{ api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ api_user }}"
            password: "{{ api_pass }}"
          id: 1
        headers:
          Content-Type: "application/json"
      register: auth_response

    - name: Verificar la respuesta de autenticación
      fail:
        msg: "Error: {{ auth_response.json.error.message }}"
      when: auth_response.json.error is defined

    - name: Crear grupo en Zabbix
      uri:
        url: "{{ api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "usergroup.create"
          params:
            name: "{{ group_name }}"
          auth: "{{ auth_response.json.result }}"
          id: 1
        headers:
          Content-Type: "application/json"
      register: group_response

    - name: Verificar la respuesta de creación de grupo
      fail:
        msg: "Error al crear el grupo de usuarios: {{ group_response.json.error.message }}"
      when: group_response.json.error is defined

    - name: Mostrar el ID del grupo creado
      debug:
        msg: "Grupo de usuarios creado exitosamente. ID del grupo de usuarios: {{ group_response.json.result.usrgrpids[0] }}"
