---
- name: Crear grupo de usuarios en Zabbix
  hosts: localhost
  gather_facts: no

  vars:
    zabbix_api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "zabbix"

    user_group_name: "MiGrupoDeUsuarios"
    hostgroup_name: "MiGrupoDeHosts"
    templategroup_name: "MiGrupoDePlantillas"

  tasks:
    - name: Obtener token de autenticación de la API de Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "user.login",
            "params": {
              "user": "{{ zabbix_api_user }}",
              "password": "{{ zabbix_api_pass }}"
            },
            "id": 1,
            "auth": null
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: auth_result

    - name: Crear grupo de usuarios en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "usergroup.create",
            "params": {
              "name": "{{ user_group_name }}"
            },
            "auth": "{{ auth_result.json.result }}",
            "id": 2
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: create_result

    - name: Obtener ID del grupo de hosts
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "hostgroup.get",
            "params": {
              "filter": {
                "name": "{{ hostgroup_name }}"
              }
            },
            "auth": "{{ auth_result.json.result }}",
            "id": 3
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: hostgroup_result

    - name: Obtener ID del grupo de plantillas
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "templategroup.get",
            "params": {
              "filter": {
                "name": "{{ templategroup_name }}"
              }
            },
            "auth": "{{ auth_result.json.result }}",
            "id": 4
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: templategroup_result

    - name: Asignar permisos de grupo de hosts al grupo de usuarios
      uri:
       ```yaml
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "usergroup.massadd",
            "params": {
              "usrgrpids": [ "{{ create_result.json.result.usrgrpids[0] }}" ],
              "rights": {
                "permission": 2,
                "id": [ "{{ hostgroup_result.json.result[0].groupid }}" ]
              }
            },
            "auth": "{{ auth_result.json.result }}",
            "id": 5
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: assign_hostgroup_result

    - name: Asignar permisos de grupo de plantillas al grupo de usuarios
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "usergroup.massadd",
            "params": {
              "usrgrpids": [ "{{ create_result.json.result.usrgrpids[0] }}" ],
              "rights": {
                "permission": 2,
                "id": [ "{{ templategroup_result.json.result[0].groupid }}" ]
              }
            },
            "auth": "{{ auth_result.json.result }}",
            "id": 6
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: assign_templategroup_result

    - debug:
        var: create_result.json
    - debug:
        var: assign_hostgroup_result.json
    - debug:
        var: assign_templategroup_result.json
