---
- name: Crear nuevo grupo en Zabbix
  hosts: localhost
  become: true
  vars:
    zabbix_api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    zabbix_username: "Admin"
    zabbix_password: "zabbix"
    zabbix_group_name: "migrupo"

  tasks:
    - name: Obtener token de autenticación en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ zabbix_username }}"
            password: "{{ zabbix_password }}"
          id: 1
          auth: null
        validate_certs: no
      register: zabbix_auth

    - name: Obtener ID del grupo "System default"
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostgroup.get"
          params:
            output: "extend"
            filter:
              name: "System default"
          auth: "{{ zabbix_auth.json.result }}"
          id: 2
        validate_certs: no
      register: zabbix_group_frontend

    - name: Crear nuevo grupo en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostgroup.create"
          params:
            name: "{{ zabbix_group_name }}"
            flags: 0
            internal: 1
            groupids:
              - "{{ zabbix_group_frontend.json.result[0].groupid }}"
          auth: "{{ zabbix_auth.json.result }}"
          id: 3
        validate_certs: no
