---
- name: Crear grupo de usuarios en Zabbix
  hosts: localhost
  gather_facts: no

  vars:
    zabbix_api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "zabbix"

    user_group_name: "MiGrupoDeUsuarios"
    hostgroup_permissions:
      - groupid: "1"  # ID del grupo de hosts
        permission: 2     # 0 - sin acceso, 2 - lectura, 3 - escritura
    users:
      - userid: "1"

  tasks:
    - name: Obtener token de autenticación de la API de Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "user.login",
            "params": {
              "user": "{{ zabbix_api_user }}",
              "password": "{{ zabbix_api_pass }}"
            },
            "id": 1,
            "auth": null
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: auth_result

    - name: Crear grupo de usuarios en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body: |
          {
            "jsonrpc": "2.0",
            "method": "usergroup.create",
            "params": {
              "name": "{{ user_group_name }}",
              "rights": [
                {
                  "permission": 2,
                  "groupid": "{{ hostgroup_permissions[0].groupid }}"
                }
              ],
              "users": {{ users | to_json }},
              "tag_filters": {}
            },
            "auth": "{{ auth_result.json.result }}",
            "id": 2
          }
        body_format: json
        headers:
          Content-Type: "application/json"
      register: create_result

    - debug:
        var: create_result.json
