---
- name: Crear usuario administrador en Zabbix
  hosts: localhost
  gather_facts: no

  vars:
    zabbix_api_url: "http://172.30.214.31/zabbix/api_jsonrpc.php"
    zabbix_api_user: "Admin"
    zabbix_api_pass: "zabbix"
    add_user_name: "ansible"
    add_user_pass: "!AlfaUno"
    add_group_name: "flexxibleit"
    role_name: "Admin role"

  tasks:
    - name: Obtener token de autenticación
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ zabbix_api_user }}"
            password: "{{ zabbix_api_pass }}"
          auth: null
          id: 1
        headers:
          Content-Type: "application/json-rpc"
        return_content: yes
        validate_certs: no
      register: auth_token_result

    - name: Obtener ID del grupo de usuarios
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "usergroup.get"
          params:
            output: ["usrgrpid"]
            filter:
              name: "{{ add_group_name }}"
          auth: "{{ auth_token_result.json.result }}"
          id: 1
        headers:
          Content-Type: "application/json-rpc"
        return_content: yes
        validate_certs: no
      register: group_result

    - name: Obtener roles de usuario
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "role.get"
          params:
            output: ["roleid", "name"]
          auth: "{{ auth_token_result.json.result }}"
          id: 1
        headers:
          Content-Type: "application/json-rpc"
        return_content: yes
        validate_certs: no
      register: role_result

    - name: Buscar ID del rol por nombre
      set_fact:
        role_id: "{{ (role_result.json.result | selectattr('name', 'equalto', role_name) | list)[0].roleid }}"
      vars:
        role_name: "{{ role_name }}"
      when: role_result.json.result | selectattr('name', 'equalto', role_name) | list | count > 0

    - fail:
        msg: "El rol '{{ role_name }}' no fue encontrado en Zabbix."
      when: role_id is undefined

    - name: Crear el usuario en Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.create"
          params:
            alias: "{{ add_user_name }}"
            passwd: "{{ add_user_pass }}"
            usrgrps:
              - usrgrpid: "{{ group_result.json.result[0].usrgrpid }}"
            roleid: "{{ role_id }}"
          auth: "{{ auth_token_result.json.result }}"
          id: 1
        headers:
          Content-Type: "application/json-rpc"
        return_content: yes
        validate_certs: no
      register: create_user_result

    - debug:
        var: create_user_result.json
