---
- name: Zabbix
  #hosts: '{{ worker }}'
  hosts: master
  become: yes
  vars:
    ansible_become_password: "{{ ansible_ssh_pass }}"

  tasks:
    - name: Actualizar repositorios
      yum:
        name: "*"
        state: latest
      register: resultado_actualizacion
      until: resultado_actualizacion is succeeded

    - name: Instalar paquetes necesarios
      yum:
        name:
          - epel
          - httpd
          - mariadb
          - mariadb-server
          - php
          - php-mysqlnd
          - php-ldap
          - php-bcmath
          - php-mbstring
          - php-gd
          - php-xml
          - php-json
        state: latest

    - name: Iniciar y habilitar servicios
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - httpd
        - mariadb

    - name: Descargar Zabbix repository
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
        dest: /tmp/zabbix-release-6.4-1.el9.noarch.rpm

    - name: Instalar repositorio de Zabbix
      yum:
        name: /tmp/zabbix-release-6.4-1.el9.noarch.rpm
        state: present

    - name: Instalar Zabbix Server
      yum:
        name: zabbix-server-mysql
        state: latest

    - name: Instalar Zabbix Web
      yum:
        name: zabbix-web-mysql
        state: latest

    - name: Crear base de datos para Zabbix
      mysql_db:
        name: zabbix
        state: present
      become_user: root
      become_method: sudo

    - name: Crear usuario y asignar permisos para la base de datos de Zabbix
      mysql_user:
        name: zabbix
        password: zabbix
        priv: "zabbix.*:ALL"
        state: present
      become_user: root
      become_method: sudo

    - name: Importar datos iniciales en la base de datos de Zabbix
      command: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u zabbix -pzabbix zabbix
      become_user: root
      become_method: sudo

    - name: Configurar archivo de configuración de Zabbix Server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^# DBHost=', line: 'DBHost=localhost' }
        - { regexp: '^# DBName=', line: 'DBName=zabbix' }
        - { regexp: '^# DBUser=', line: 'DBUser=zabbix' }
        - { regexp: '^# DBPassword=', line: 'DBPassword=zabbix' }

    - name: Configurar archivo de configuración de Zabbix Web
      lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^# php_value date.timezone', line: 'php_value date.timezone America/New_York' }
