- name: Filtrar ID del rol por nombre
  set_fact:
    role_id: "{{ (role_result.json.result | selectattr('name', 'equalto', zabbix_role_name) | list)[0].roleid }}"
#  vars:
#    zabbix_role_name: "{{ zabbix_role_name }}"
  when: role_result.json.result | selectattr('name', 'equalto', zabbix_role_name) | list | count > 0

- fail:
    msg: El rol "{{ zabbix_role_name }}" no fue encontrado en Zabbix.
  when: role_id is undefined