- name: Obtener ID rol de usuario
  uri:
    url: "{{ zabbix_api_url }}"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "role.get"
      params:
        output: ["roleid", "name"]
        filter:
          name: "{{ role_name }}"
      auth: "{{ auth_response.json.result }}"
      id: 1
    headers:
      Content-Type: "application/json-rpc"
    return_content: yes
    validate_certs: no
  register: role_result

- debug:
    var: role_result.json.result

- name: Buscar ID del rol por nombre
  set_fact:
    add_role_id: "{{ (role_result.json.result | selectattr('name', 'equalto', add_role_name) | list)[0].roleid }}"
  vars:
    add_role_name: "{{ add_role_name }}"
  when: role_result.json.result | selectattr('name', 'equalto', add_role_name) | list | count > 0

- fail:
    msg: "El rol '{{ add_role_name }}' no fue encontrado en Zabbix."
  when: add_role_id is undefined