- name: Descargar del asistente del repositorio ZABBIX
  get_url:
    url: https://repo.zabbix.com/zabbix/6.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.5-1+2Bubuntu22.04_all.deb
    dest: /tmp/install_repo_zabbix.deb
  when: "{{ version}}" == "7.0"

- name: Descargar del asistente del repositorio ZABBIX
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    dest: /tmp/install_repo_zabbix.deb
  when: "{{ version}}" == "6.4"

- name: Descargar del asistente del repositorio ZABBIX
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
    dest: /tmp/install_repo_zabbix.deb
  when: "{{ version}}" == "6.0"

- name: Instalar repo Zabbix
  apt:
    deb: /tmp/install_repo_zabbix.deb
    state: present

- name: Actualizar lista de paquetes
  apt:
    update_cache: yes

- name: Install Modules Zabbix
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present
