- name: Descargar del asistente del repositorio ZABBIX
  get_url:
    url: https://repo.zabbix.com/zabbix/6.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.5-1%2Bubuntu22.04_all.deb
    dest: /tmp/install_repo_zabbix.rpm

- name: Instalar el asistente
  yum:
    deb: /tmp/install_repo_zabbix.rpm
    state: present

- name: Actualizar lista de paquetes
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install Modules Zabbix
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present
