### INSTALAR DEPENDENCIAS
### FIX WEB LOCALE UTC-8
### RECARGA DE SERVICIOS
### CONFIGURACION DE PHP
### INSTALACION ZABBIX
### IMPORTA CONF. ZABBIX
### CONFIGURACION DE LA BASE DE DATOS ZABBIX
### RECARGA DE SERVICIOS

### SUPPORT DEBIAN
### SUPPORT UBUNTU
---

- name: INSTALL DEPENDENCIAS
  include_tasks: install_dependencias_debian.yml
  when: ansible_os_family == "Debian"

- name: CONFIGURACION LOCALE en_US.UTF-8
  include_tasks: config_locale_en_US.UTF-8.yml
  when: ansible_os_family == "Debian"

- name: RELOAD APACHE2
  include_tasks: reload_apache2.yml
  when: ansible_os_family == "Debian"

- name: RELOAD MARIADB
  include_tasks: reload_mariadb.yml
  when: ansible_os_family == "Debian"

- name: PHP-CGI
  include_tasks: config_php-cgi.yml
  when: ansible_os_family == "Debian"

- name: IMPORT PHP CONFIG
  include_tasks: import_php_config.yml
  when: ansible_os_family == "Debian"

- name: DOWNLOAD AND INSTALL ZABBIX 
  include_tasks: install_zabbix_debian.yml
  when: ansible_os_family == "Debian"

- name: IMPORT CONFIG ZABBIX 
  include_tasks: import_config_zabbix.yml
  when: ansible_os_family == "Debian"

- name: CONFIG MARIADB
  include_tasks: config_mariadb_7.0.yml
  when: ansible_os_family == "Debian" and version == '7.0'

- name: CONFIG MARIADB
  include_tasks: config_mariadb_6.4.yml
  when: ansible_os_family == "Debian" and version == '6.4'

- name: CONFIG MARIADB
  include_tasks: config_mariadb_6.0.yml
  when: ansible_os_family == "Debian" and version == '6.0'



- name: RELOAD ZABBIX
  include_tasks: reload_zabbix.yml
  when: ansible_os_family == "Debian"

- name: RELOAD AGENT
  include_tasks: reload_agent.yml
  when: ansible_os_family == "Debian"

- name: RELOAD APACHE2
  include_tasks: reload_apache2.yml
  when: ansible_os_family == "Debian"


### SUPPORT REDHAT
### SUPPORT ALMALINUX


- name: INSTALL DEPENDENCIAS
  include_tasks: install_dependencias_redhat.yml
  when: ansible_os_family == "RedHat"

#- name: CONFIGURACION LOCALE en_US.UTF-8
#  include_tasks: config_locale_en_US.UTF-8.yml
#  when: ansible_os_family == "RedHat"

- name: RELOAD APACHE2
  include_tasks: reload_httpd.yml
  when: ansible_os_family == "RedHat"

- name: RELOAD MARIADB
  include_tasks: reload_mariadb.yml
  when: ansible_os_family == "RedHat"

#- name: PHP-CGI
#  include_tasks: config_php-cgi.yml
#  when: ansible_os_family == "RedHat"

- name: IMPORT PHP CONFIG
  include_tasks: import_php_config.yml
  when: ansible_os_family == "RedHat"

- name: DOWNLOAD AND INSTALL ZABBIX 
  include_tasks: install_zabbix_redhat.yml
  when: ansible_os_family == "RedHat"

- name: IMPORT CONFIG ZABBIX 
  include_tasks: import_config_zabbix.yml
  when: ansible_os_family == "RedHat"

- name: CONFIG MARIADB
  include_tasks: config_mariadb.yml
  when: ansible_os_family == "RedHat"

- name: RELOAD ZABBIX
  include_tasks: reload_zabbix.yml
  when: ansible_os_family == "RedHat"

- name: RELOAD AGENT
  include_tasks: reload_agent.yml
  when: ansible_os_family == "RedHat"

- name: RELOAD APACHE2
  include_tasks: reload_httpd.yml
  when: ansible_os_family == "RedHat"


